version: '3.9'

services:
  backend:
    build: .

    ports:
      - '3000:3000'

    environment:
      DATABASE_URL: postgresql://nick:eboy@db:5432/workout_app?schema=public

    depends_on:
      - db

    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:16

    restart: always

    environment:
      POSTGRES_USER: nick
      POSTGRES_PASSWORD: eboy
      POSTGRES_DB: workout_app

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
